---
#https://docs.ansible.com/ansible/2.3/include_vars_module.html
- name: "Load a variable file based on the OS type, or a default if not found"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    -  "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
    - default.yml


- name: "Install system packages"
  package:
    name: '{{ system_packages }}'
    use: '{{ ansible_pkg_mgr }}'
    state: present

- name: "Upgrade all packages"
  yum:
    name: '*'
    state: latest 

- name: "Add GoCD YUM Repository"
  yum_repository:
    name:  gocd
    description:  GoCD YUM Repository
    baseurl:   https://download.gocd.io
    enabled:   1
    gpgcheck:  1
    gpgkey:    https://download.gocd.io/GOCD-GPG-KEY.asc
    state: present

- name: "Ensure /var/go folder exists"
  file: 
    path: "/var/go"
    state: directory

- name: "Install go-server and JDK"
  yum: 
    name: ['java-1.8.0-openjdk','go-server']  
    state: latest

- name: "Ensure that Go-server starts at startup and is started"
  service: 
    name: go-server 
    enabled: yes 
    state: started 