---
#https://docs.ansible.com/ansible/2.3/include_vars_module.html
- name: "Load a variable file based on the OS type, or a default if not found"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    -  "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
    - default.yml


- name: "Install system packages"
  package:
    name: '{{ system_packages }}'
    use: '{{ ansible_pkg_mgr }}'
    state: present

- name: "Install packages"
  package:
    name: "{{ item }}"
    state: present
    with_items:
    - go-server

- name: "Enable and start go-server"
  service:
    name: go-server
    enabled: yes
    state: started

