---
sudo: required
notifications:
  slack:
    on_failure: always

matrix:
  fast_finish: true
  include:  

    - name: "deploy jenkins centos 8"
      dist: bionic
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
          - sudo make deploy-libvirt
          - sudo make deploy-vagrant
          - sudo make deploy-boxes
      after_success:
        - deactivate                

    # - name: "deploy gocd server and agents"
    #   dist: bionic
    #   language: python
    #   python: 3.7
    #   before_install:
    #     - pip3 install virtualenv
    #     - virtualenv -p $(which python3) ~venvpy3
    #     - source ~venvpy3/bin/activate
    #     - pip install -r requirements.txt
    #   script:
    #       - sudo make deploy-libvirt
    #       - sudo make deploy-vagrant
    #       - sudo make deploy-topology
    #       # - travis_wait 20 waitfortrav.sh
    #   after_success:
    #     - deactivate    

    # - name: "deploy gocd server docker-compose"
    #   dist: bionic
    #   language: python
    #   python: 3.7
    #   before_install:
    #     - pip3 install virtualenv
    #     - virtualenv -p $(which python3) ~venvpy3
    #     - source ~venvpy3/bin/activate
    #     - pip install -r requirements.txt
    #   script:
    #       - docker-compose up
    #       - curl http://localhost
    #       # - curl -X POST http://localhost/go/api/admin/pipelines -H 'Accept: application/vnd.go.cd.v4+json' -H 'Content-Type: application/json' -d @example-pipeline.json
    #       # - travis_wait 20 waitfortrav.sh
    #   after_success:
    #     - deactivate                