---
sudo: required
notifications:
  slack:
    on_failure: always

matrix:
  fast_finish: true
  include:  

    - name: "deploy Jenkins with Docker"
      dist: bionic
      language: python
      python: 3.7
      services: docker
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
          - docker run -p 8080:8080 -p 50000:50000 -v ~/jenkins_home:/var/jenkins_home jenkins/jenkins:lts
          - sudo docker exec ${CONTAINER_ID or CONTAINER_NAME} cat /var/jenkins_home/secrets/initialAdminPassword
          # - curl http://localhost:8080
      after_success:
        - deactivate
        - sudo vagrant destroy -f # required to run Vagrantfile template        
        - sudo rm Vagrantfile # required to run Vagrantfile template 
                