---

- name: Ensure old versions of Docker are not installed.
  yum:
    name:
      - docker
      - docker-common
      - docker-engine
    state: absent
  become: yes
  # become_user: jenkins-slave1
  # become_method: sudo

- name: Add Docker GPG key.
  rpm_key:
    key: "{{ docker_yum_gpg_key }}"
    state: present

- name: Add Docker repository.
  get_url:
    url: "{{ docker_yum_repo_url }}"
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    owner: root
    group: root
    mode: 0644

# - name: Configure containerd on RHEL 8.
#   block:
#     - name: Ensure container-selinux is installed.
#       package:
#         name: container-selinux
#         state: present

- name: "Ensure containerd.io is installed."
  yum:
    name:
      - containerd.io
    state: present

# - name: "Ensure containerd.io is installed."
#   package:
#     name: containerd.io
#     state: present        

