pipeline {
    agent any

    stages {
        
        stage('SCM Checkout') {
            steps {
                echo 'check out git repo'
                git branch: 'dev', url: 'https://github.com/githubfoam/jenkins-sandbox'
            }
        }
        
        stage("Deployment"){
            steps{
                ansiColor('xterm') {
                    ansiblePlaybook(
                        playbook: 'provisioning/vg-compute-07.yml',
                        inventory: 'dev.inv',
                        colorized: true,
            become: true,
            becomeUser: 'jenkins-slave1',
            extras: '-vvv'
                    )
                }
            }
        }
    }
}
