pipeline {
    agent any

    stages {
        
        stage('SCM Checkout') {
            steps {
                echo 'check out git repo'
                git branch: 'dev', url: 'https://github.com/githubfoam/jenkins-sandbox'
            }
        }
        
        stage('Execute Ansible') {
            steps{
                ansiblePlaybook credentialsId: '4b288511-8145-48f4-8890-28b0ac79f6ae', disableHostKeyChecking: true, installation: 'ansible', inventory: 'dev.inv', playbook: 'provisioning/vg-compute-07.yml'
            }
            
        }
        stage("Deployment"){
            steps{
                ansiColor('xterm') {
                    ansiblePlaybook(
                        playbook: 'provisioning/vg-compute-07.yml',
                        inventory: 'dev.inv',
                        colorized: true,
            become: true,
            becomeUser: 'jenkins-slave1',
            extras: '-vvv'
                    )
                }
            }
        }
    }
}
