---
- name: "deploy jenkins w ansible role"
  gather_facts: true
  hosts: vg-compute-10
  become: yes
  roles:
    - common
    - jenkins   
 
- name: "deploy dockerized jenkins"
  gather_facts: true
  hosts: vg-compute-11
  become: yes
  roles:
    - common
    - docker   
 