---
- name: "deploy jenkins w ansible role"
  gather_facts: true
  hosts: vg-compute-10
  become: yes
  roles:
    - common
    - jenkins   
 
- name: "deploy dockerized jenkins"
  gather_facts: true
  hosts: vg-compute-11
  become: yes
  roles:
    - common
    - docker   
    - docker-jenkins
 
- name: "deploy docker-jenkins ansible role" #cd server
  gather_facts: true
  hosts: vg-compute-12
  become: yes
  roles:
    - common
    - docker  
    - docker-registry
    - docker-jenkins
    