name: "Ubuntu jenkins docker CI workflow"


on:
  push:
    branches: [ master ]


jobs:

# #https://support.nagios.com/kb/article/nagios-core-installing-nagios-core-from-source-96.html#Ubuntu
#   ubuntu-1604-nagios-docker-job:
#     name: "ubuntu-16.04 nagios docker job"
#     runs-on: ubuntu-16.04
#     steps:
#     - uses: actions/checkout@v2
#     - name: "os fingerprinting"
#       run: hostnamectl status    
#     - name: "Pull Jenkins from the public repo"
#       run: sudo docker pull jenkins/jenkins              
#     - name: "Run jenkins image"
#       run: sudo docker run -p 8080:8080 --name=jenkins-master jenkins/jenkins     
#     - name: "Get initial password" # http://localhost:8080
#       run: sudo docker exec jenkins-master cat /var/jenkins_home/secrets/initialAdminPassword     


#   ubuntu-1804-nagios-docker-job:
#     name: "ubuntu-18.04 nagios docker prod job"
#     runs-on: ubuntu-18.04
#     steps:
#     - uses: actions/checkout@v2
#     - name: "os fingerprinting"
#       run: hostnamectl status   
#     - name: "Pull Jenkins from the public repo"
#       run: sudo docker pull jenkins/jenkins              
#     - name: "Run jenkins image"
#       run: sudo docker run -p 8080:8080 --name=jenkins-master jenkins/jenkins     
#     - name: "Get initial password" # http://localhost:8080
#       run: sudo docker exec jenkins-master cat /var/jenkins_home/secrets/initialAdminPassword     



  ubuntu-2004-nagios-docker-job:
    name: "ubuntu-20.04 nagios docker prod job"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status   
    - name: "Pull Jenkins from the public repo"
      run: sudo docker pull jenkins/jenkins              
    - name: "Run jenkins image"
      run: sudo docker run -p 8080:8080 --name=jenkins-master jenkins/jenkins     
    - name: "Get initial password" # http://localhost:8080
      run: sudo docker exec jenkins-master cat /var/jenkins_home/secrets/initialAdminPassword     

