---

- name: Package are present
  yum:
    name=java-1.8.0-openjdk
    state=present
  with_items: packages

- name: Directories are present
  file:
    path="{{ item }}"
    state=directory
    mode=0777
  with_items: "{{ directories }}"
  # tags: [jenkins]

# - name: Config files are present
#   copy:
#     src='{{ item }}'
#     dest='{{ jenkins_directory }}/{{ item }}'
#     mode=0777
#   with_items: "{{ configs }}"
#   tags: [jenkins]

# - name: Plugins are present
#   copy:
#     src='{{ item }}'
#     dest='{{ jenkins_directory }}/plugins/{{ item }}'
#     mode=0777
#   with_items: "{{ plugins }}"
#   tags: [jenkins]

# - name: Build job directories are present
#   file:
#     path='{{ jenkins_directory }}/jobs/{{ item }}'
#     state=directory
#     mode=0777
#   with_items: "{{ jobs }}"
#   tags: [jenkins]

# - name: Build jobs are present
#   template:
#     src=build.xml.j2
#     dest='{{ jenkins_directory }}/jobs/{{ item }}/config.xml'
#     mode=0777
#     backup=yes
#   with_items: "{{ jobs }}"
#   tags: [jenkins]

# - name: Deployment job directories are present
#   file:
#     path='{{ jenkins_directory }}/jobs/{{ item }}-deployment'
#     state=directory
#     mode=0777
#   with_items: "{{ jobs }}"
#   tags: [jenkins]

# - name: Deployment jobs are present
#   template:
#     src=deployment.xml.j2
#     dest='{{ jenkins_directory }}/jobs/{{ item }}-deployment/config.xml'
#     backup=yes
#     mode=0777
#   with_items: "{{ jobs }}"
#   tags: [jenkins]

- name: Install Docker SDK for Python
  pip:
    name: "docker<5" 

- name: Docker service is restarted
  service:
    name: docker
    state: restarted

- name: Pull the latest official jenkins docker image
  docker_image:
    name: "jenkins/jenkins:lts-jdk11"
    source: pull

# - name: Create a container from the jenkins docker image
#   docker_container:
#     name=jenkinsci
#     image=jenkins/jenkins:lts-jdk11
#     ports:
#         - "8080:8080"
#         - "50000:50000"
#     volumes=/data/jenkins:/var/jenkins_home
#   tags: [jenkins]

- name: Create a container from the jenkins docker image
  docker_container:
    name: "jenkinsci"
    image: "jenkins/jenkins:lts-jdk11"
    detach: yes
    ports:
        - "8080:8080"
        - "50000:50000"
    volumes:
        - "/data/jenkins:/var/jenkins_home"
    state: started
    recreate: no
  # tags: [jenkins]

- name: Get infos on container
  docker_container_info:
    name: jenkinsci
  register: result

- name: Does container exist?
  debug:
    msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"

- name: Print information about container
  debug:
    var: result.container
  when: result.exists



# - name: Restart container
#   docker_container:
#     name: "jenkinsci"
#     image: "jenkins/jenkins:lts-jdk11"
#     detach: yes
#     ports:
#         - "8080:8080"
#         - "50000:50000"
#     volumes:
#         - "/data/jenkins:/var/jenkins_home"
#     state: started
#     restart: yes
#     recreate: no
#   # tags: [jenkins]

 