---
#
# Installing Jenkins
#
- name: Prepare
  block:
    - name: "Install requirements"
      package:
        name: '{{ jenkins_requirements }}'
        state: present
      register: status
      until: status is succeeded

    - name: Upgrade pip
      pip:
        name:
          - pip
        state: present
        extra_args: --upgrade
        executable: 'pip{{ ansible_facts.python.version.major }}'
      register: installed_packages
      until: installed_packages is success

    - name: Install pip packages
      pip:
        name:
          - pyOpenSSL
          - python-jenkins
          - lxml
        state: present
        executable: 'pip{{ ansible_facts.python.version.major }}'
      register: installed_packages
      until: installed_packages is success

    - name: "Create group"
      group:
        name: '{{ jenkins2_user | default("jenkins") }}'
        state: present

    - name: "Create user"
      user:
        name: '{{ jenkins2_user | default("jenkins") }}'
        group: '{{ jenkins2_user | default("jenkins") }}'
        shell: /bin/bash
        home: '{{ jenkins2_home_directory }}'

    - name: Create symlink
      file:
        src: '{{ jenkins2_home_directory }}'
        dest: /var/lib/jenkins
        owner: '{{ jenkins2_user | default("jenkins") }}'
        group: '{{ jenkins2_user | default("jenkins") }}'
        state: link
      when: jenkins2_home_directory != '/var/lib/jenkins'        

    - name: Jenkins Key
      apt_key:
        url: '{{ jenkins_deb_repo_key }}'
        validate_certs: '{{ jenkins2_key_validate_certs }}'
        state: present
      environment:
        http_proxy: '{{ jenkins2_proxy_url }}'
        HTTP_PROXY: '{{ jenkins2_proxy_url }}'
        https_proxy: '{{ jenkins2_proxy_url }}'
        HTTPS_PROXY: '{{ jenkins2_proxy_url }}'
      register: status
      retries: 10
      delay: 3
      until: status is succeeded


    - name: Jenkins Repository
      apt_repository:
        repo: '{{ jenkins_deb_repo_url }}'
        update_cache: true
        state: present
      register: status
      retries: 10
      delay: 3
      until: status is succeeded

    - name: Jenkins Installation
      package:
        name: '{{ jenkins2_package_version }}'
        state: present
      register: jenkins_was_installed
      until: jenkins_was_installed is succeeded   

    - name: Apply Jenkins configuration file
      template:
        src: 'jenkins_system_config/{{ ansible_os_family }}_configuration.j2'
        dest: '{{ jenkins_config_service_path }}'
        # owner: root
        # group: root
        # mode: 0644
        backup: true
      notify:
        - Restart Jenkins      